/* Synthetic, deterministic data for the Mal Principal Business Intelligence case study. No customer or bank data is used. */
const BI_DATA = {
  asOf: '31 Jul 2026',
  months: ['Aug 25','Sep 25','Oct 25','Nov 25','Dec 25','Jan 26','Feb 26','Mar 26','Apr 26','May 26','Jun 26','Jul 26'],
  activeCustomers: [11980,12420,12970,13410,14080,14620,15110,15690,16260,16920,17410,18640],
  customerBalances: [51.2,54.8,57.4,60.8,63.1,67.5,70.9,75.4,79.1,84.7,89.2,94.8],
  financingBook: [94.4,98.2,102.9,107.8,112.3,117.9,122.4,127.3,131.6,136.4,140.1,142.6],
  par30: [2.7,2.8,2.7,2.6,2.7,2.5,2.6,2.5,2.5,2.4,2.5,2.4],
  financingIncome: [3.15,3.36,3.52,3.66,3.98,4.16,4.48,4.71,5.04,5.43,5.82,6.42],
  kpis: [
    {label:'Certified active customers', value:'18,640', delta:'+7.1% QoQ', trend:'good', domain:'Enterprise', status:'Certified', note:'Enterprise Active Customer'},
    {label:'Net financing income', value:'AED 6.42m', delta:'+10.3% MoM', trend:'good', domain:'Finance', status:'Certified', note:'Profit and service income, net of incentives'},
    {label:'Customer balances', value:'AED 94.8m', delta:'+6.3% MoM', trend:'good', domain:'Finance', status:'Certified', note:'Closing eligible customer balances'},
    {label:'Gross financing book', value:'AED 142.6m', delta:'+1.8% MoM', trend:'good', domain:'Credit', status:'Certified', note:'Outstanding financing principal'},
    {label:'Financing approval rate', value:'61.8%', delta:'+1.2pp vs floor', trend:'good', domain:'Credit', status:'Certified', note:'Final approvals / adjudicated decisions'},
    {label:'PAR30', value:'2.4%', delta:'−0.2pp YoY', trend:'good', domain:'Risk', status:'Certified', note:'30+ DPD principal / gross financing book'},
    {label:'Digital activation', value:'74.6%', delta:'+2.9pp QoQ', trend:'good', domain:'Product', status:'Certified', note:'Activated in 7 days'},
    {label:'New-to-bank share', value:'43.8%', delta:'+2.1pp QoQ', trend:'good', domain:'Inclusion', status:'Certified', note:'Verified customers new to formal banking'},
    {label:'Sharia control exceptions', value:'0', delta:'Within zero-tolerance', trend:'good', domain:'Sharia', status:'Certified', note:'Confirmed control exceptions this month'}
  ],
  incomeMix: [{name:'Financing profit income',value:3.04,color:'#155e59'},{name:'Payment & service income',value:1.46,color:'#39a293'},{name:'Balance-product income',value:1.12,color:'#8b7ad7'},{name:'Financing service fees',value:0.80,color:'#d39a41'}],
  funnel: [{name:'Applications started',value:12840,percent:100},{name:'Submitted',value:9640,percent:75.1},{name:'Adjudicated',value:8430,percent:65.7},{name:'Approved',value:5210,percent:40.6},{name:'Disbursed',value:4760,percent:37.1}],
  riskSegments: [{name:'New-to-Finance',value:2.8,limit:3.0},{name:'Repeat customer',value:1.7,limit:3.0},{name:'Payroll-linked',value:0.9,limit:3.0}],
  vintage: {labels:['Feb 26','Mar 26','Apr 26','May 26','Jun 26','Jul 26'], values:[2.2,2.5,2.3,2.6,2.7,2.4]},
  definitions: [
    {team:'Finance',metric:'Income-generating customer',value:'16,980',status:'Exploratory',rule:'Customer with ≥1 settled profit- or fee-generating event in the month.',why:'Useful for financing-profit and service-income attribution; excludes financing customers with no payment event.',accent:'amber'},
    {team:'Product',metric:'Engaged user',value:'17,420',status:'Exploratory',rule:'Customer with ≥2 meaningful app events in trailing 30 days.',why:'Useful for product adoption; counts journeys even if no financial activity occurred.',accent:'violet'},
    {team:'Credit',metric:'Active financing customer',value:'7,860',status:'Exploratory',rule:'Customer with financing principal outstanding at month-end.',why:'Useful for portfolio management; intentionally limited to financing customers.',accent:'teal'}
  ],
  metrics: [
    ['KPI-01 · Enterprise Active Customer','Enterprise','Product Analytics','Unique verified customer with ≥1 posted payment transaction OR open financing principal at calendar month-end; fraud-confirmed and closed accounts excluded.','COUNT(DISTINCT customer_id WHERE posted_txn OR open_financing_principal_eom)','mart_customer_monthly','Daily 06:00 GST','Certified'],
    ['KPI-02 · Total Customer Base','Enterprise','Product Analytics','Unique verified customers with any open product or historical completed onboarding.','COUNT(DISTINCT verified_customer_id)','dim_customer','Daily 06:00 GST','Certified'],
    ['KPI-03 · Customer Retention','Product','Product Analytics','Prior-month certified active customers also certified active in the current month.','retained_active / prior_month_active','mart_customer_monthly','Monthly +1','Certified'],
    ['KPI-04 · Net Financing Income','Finance','Finance Control','Recognised financing-profit and service income less customer incentives and reversals in the month; excludes prohibited income.','SUM(financing_profit + service_income) − SUM(incentives + reversals)','mart_finance_monthly','Month-end +2','Certified'],
    ['KPI-05 · Customer Balances','Finance','Treasury','Eligible customer balance principal at end of calendar day; excludes internal and suspense accounts.','SUM(eligible_customer_balance_eod)','mart_finance_daily','Daily 06:15 GST','Certified'],
    ['KPI-06 · Cost-to-Income Ratio','Finance','Finance Control','Operating expenses divided by net financing income for the reporting period.','operating_expense / net_financing_income','mart_finance_monthly','Month-end +3','Certified'],
    ['KPI-07 · Financing Approval Rate','Credit','Credit Operations','Final approved financing applications as a share of applications with a final approve/decline outcome; withdrawals and pending cases excluded.','approved / (approved + declined)','mart_financing_application_daily','Daily 06:30 GST','Certified'],
    ['KPI-08 · Disbursed Conversion','Credit','Credit Operations','Approved financing applications that reached disbursement within 30 days.','disbursed_30d / approved','mart_financing_application_daily','Daily 06:30 GST','Certified'],
    ['KPI-09 · Gross Financing Book','Credit','Credit Finance','Outstanding financing principal before expected-credit-loss provisions, including contractual arrears.','SUM(financing_principal_outstanding_eod)','mart_financing_portfolio_daily','Daily 06:30 GST','Certified'],
    ['KPI-10 · PAR30','Risk','Credit Risk','Financing principal outstanding on contracts 30 or more days past due divided by gross financing book.','SUM(principal WHERE dpd ≥ 30) / gross_financing_book','mart_financing_portfolio_daily','Daily 06:30 GST','Certified'],
    ['KPI-11 · Net Credit Loss Rate','Risk','Credit Risk','Annualised net charged-off financing principal less recoveries divided by average gross financing book.','12 × (charge_offs − recoveries) / avg_gross_financing_book','mart_financing_portfolio_daily','Month-end +3','Certified'],
    ['KPI-12 · Early Delinquency','Risk','Credit Risk','Financing principal on contracts 1–29 days past due divided by current gross financing book; shown by risk segment.','SUM(principal WHERE 1 ≤ dpd ≤ 29) / gross_financing_book','mart_financing_portfolio_daily','Daily 06:30 GST','Exploratory'],
    ['KPI-13 · Digital Activation','Product','Product Analytics','New verified customers completing first meaningful in-app action within 7 calendar days of verification.','activated_in_7d / verified_new_customers','mart_customer_monthly','Daily 06:00 GST','Certified'],
    ['KPI-14 · Payment Success Rate','Product','Payments','Successfully posted payment attempts divided by all authorised payment attempts, excluding customer cancellations.','posted_payment_attempts / authorised_attempts','mart_payments_daily','Daily 06:05 GST','Certified'],
    ['KPI-15 · Finance Income-Generating Customer','Finance','Finance Control','Customer with one or more settled profit- or fee-generating event in the month. Finance diagnostic only.','COUNT(DISTINCT customer_id WHERE settled_income_event)','mart_finance_monthly','Month-end +2','Exploratory'],
    ['KPI-16 · Product Engaged User','Product','Product Analytics','Customer with two or more meaningful app events during trailing 30 days. Product diagnostic only.','COUNT(DISTINCT customer_id WHERE meaningful_events_30d ≥ 2)','mart_product_events_daily','Daily 06:00 GST','Exploratory'],
    ['KPI-17 · Active Financing Customer','Credit','Credit Operations','Customer with financing principal outstanding at final calendar day of the month. Credit diagnostic only.','COUNT(DISTINCT customer_id WHERE financing_principal_eom > 0)','mart_financing_portfolio_daily','Daily 06:30 GST','Exploratory'],
    ['KPI-18 · Data Freshness SLA','Enterprise','Principal Business Intelligence','Share of certified data products refreshed by their published SLA.','on_time_certified_marts / certified_marts','bi_observability_daily','Daily 07:00 GST','Certified'],
    ['KPI-19 · Data Quality Pass Rate','Enterprise','Principal Business Intelligence','Share of active critical data quality tests passing on the latest successful refresh.','passing_critical_tests / critical_tests_run','bi_observability_daily','Daily 07:00 GST','Certified'],
    ['KPI-20 · New-to-Bank Share','Inclusion','Customer Strategy','Verified new customers who self-declare no active formal banking relationship in the prior 12 months.','new_to_bank_verified_customers / verified_new_customers','mart_customer_monthly','Monthly +1','Certified'],
    ['KPI-21 · Sharia Control Exceptions','Sharia','Sharia Governance','Confirmed breaches of approved product, transaction, or income controls in the reporting period.','COUNT(confirmed_sharia_exception_id)','mart_sharia_controls_daily','Daily 07:00 GST','Certified'],
    ['KPI-22 · AI Decision Explanation Coverage','Responsible AI','Responsible AI Governance','Qualifying automated customer decisions delivered with a customer-facing explanation and reason code.','explained_qualifying_ai_decisions / qualifying_ai_decisions','mart_ai_decision_daily','Daily 07:15 GST','Certified'],
    ['KPI-23 · AI Decision Fairness Gap','Responsible AI','Responsible AI Governance','Largest absolute approval-rate gap between approved protected-segment cohorts after controlling for risk band; monitoring metric only.','MAX(ABS(segment_approval_rate − reference_rate))','mart_ai_decision_daily','Monthly +3','Exploratory'],
    ['KPI-24 · AI-assisted Resolution Rate','Responsible AI','Customer Operations','Customer support cases fully resolved through approved AI-assisted journeys without a human handoff within 7 days.','ai_resolved_cases / eligible_cases','mart_support_daily','Daily 08:00 GST','Certified'],
    ['KPI-25 · KYC Completion Rate','Inclusion','Onboarding Operations','Customers initiating verification who complete required KYC checks within 7 calendar days; declined KYC cases remain in denominator.','kyc_completed_7d / kyc_started','mart_onboarding_daily','Daily 06:10 GST','Certified'],
    ['KPI-26 · Customer Complaint Resolution SLA','Trust','Customer Operations','Eligible complaints resolved within the published service-level agreement.','complaints_resolved_within_sla / eligible_complaints','mart_support_daily','Daily 08:00 GST','Certified']
  ]
};
